import sqlite3
import pandas as pd
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import os

# ─── CONFIG — Change these ─────────────────────────
SENDER_EMAIL    = "afridahamed205@gmail.com"       # Your Gmail
SENDER_PASSWORD = "toia moco vpeg srbv"     # Gmail App Password
RECEIVER_EMAIL  = "Afridahamed114@gmail.com"   # Where to send report
# ───────────────────────────────────────────────────

def get_todays_attendance():
    today = datetime.now().strftime("%Y-%m-%d")
    conn  = sqlite3.connect("attendance.db")
    df    = pd.read_sql_query(
        "SELECT name, date, time, status FROM attendance WHERE date=? ORDER BY time",
        conn, params=(today,)
    )
    conn.close()
    return df, today

def save_csv(df, today):
    filename = f"attendance_{today}.csv"
    df.to_csv(filename, index=False)
    return filename

def build_html_table(df):
    if df.empty:
        return "<p>No attendance recorded today.</p>"
    rows = ""
    for _, row in df.iterrows():
        rows += f"""
        <tr>
            <td style='padding:8px;border:1px solid #ddd'>{row['name']}</td>
            <td style='padding:8px;border:1px solid #ddd'>{row['date']}</td>
            <td style='padding:8px;border:1px solid #ddd'>{row['time']}</td>
            <td style='padding:8px;border:1px solid #ddd;color:green'>{row['status']}</td>
        </tr>"""
    return f"""
    <table style='border-collapse:collapse;width:100%'>
        <tr style='background:#4CAF50;color:white'>
            <th style='padding:10px'>Name</th>
            <th style='padding:10px'>Date</th>
            <th style='padding:10px'>Time</th>
            <th style='padding:10px'>Status</th>
        </tr>
        {rows}
    </table>"""

def send_email():
    df, today = get_todays_attendance()
    total     = len(df)
    unique    = df['name'].nunique() if not df.empty else 0

    # ── Build email ───────────────────────────────
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📋 Attendance Report — {today}"
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = RECEIVER_EMAIL

    html = f"""
    <html><body style='font-family:Arial,sans-serif'>
        <h2 style='color:#4CAF50'>📋 Daily Attendance Report</h2>
        <p><b>Date:</b> {today}</p>
        <p><b>Total Records:</b> {total} &nbsp;|&nbsp;
           <b>Unique Students:</b> {unique}</p>
        <br>
        {build_html_table(df)}
        <br>
        <p style='color:gray;font-size:12px'>
            Generated by Automated Attendance System
        </p>
    </body></html>"""

    msg.attach(MIMEText(html, "html"))

    # ── Attach CSV ────────────────────────────────
    if not df.empty:
        csv_file = save_csv(df, today)
        with open(csv_file, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition",
                            f"attachment; filename={csv_file}")
            msg.attach(part)
        os.remove(csv_file)  # clean up

    # ── Send ──────────────────────────────────────
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        print(f"[SUCCESS] Report sent to {RECEIVER_EMAIL}")
        print(f"[INFO] Total present today: {total}")
    except Exception as e:
        print(f"[ERROR] Failed to send email: {e}")
        print("[TIP] Make sure you use Gmail App Password, not your login password!")

send_email()